

const bist100 = {
    "Borsa İstanbul": {
        "processed_industries_sector": {
            "PETKM.IS": "Petkim Petrokimya Holding",
            "AKSA.IS": "Aksa Akrilik Kimya Sanayi",
            "HEKTS.IS": "Hektaş Ticaret T.A.Ş.",
            "IEYHO.IS": "Işıklar Enerji ve Yapı Holding",
            "SASA.IS": "Sasa Polyester Sanayi",
            "GUBRF.IS": "Gübre Fabrikaları T.A.Ş.",
        },
        "telecommunication_sector": {
            "TTKOM.IS": "Türk Telekomünikasyon A.Ş.",
            "TCELL.IS": "Turkcell İletişim Hizmetleri A.Ş.",
        },
        "manufacturing_sector": {
            "TTRAK.IS": "Türk Traktör ve Ziraat Makinaları A.Ş.",
            "TMSN.IS": "Tümosan Motor ve Traktör Sanayi A.Ş.",
            "EUPWR.IS": "Europower Enerji ve Otomasyon Sanayi A.Ş.",
            "ASTOR.IS": "Astor Enerji A.Ş.",
            "BERA.IS": "Bera Holding A.Ş.",
            "EGEEN.IS": "Ege Endüstri ve Ticaret A.Ş.",
            "KARSN.IS": "Karsan Otomotiv Sanayi ve Ticaret A.Ş.",
            "KLSER.IS": "Kaleseramik A.Ş.",
            "BRYAT.IS": "Borusan Yatırım ve Pazarlama A.Ş.",
        },
        "consumer_services_sector": {
            "NTHOL.IS": "Net Holding A.Ş.",
            "TABGD.IS": "Tab Gıda Sanayi ve Ticaret A.Ş.",
            "FENER.IS": "Fenerbahçe Futbol A.Ş.",
        },
        "technology_services_sector": {
            "ARDYZ.IS": "ARD Grup Bilişim Teknolojileri A.Ş.",
            "AGROT.IS": "Agrotech Teknoloji A.Ş.",
            "MIATK.IS": "Mia Teknoloji A.Ş.",
            "REEDR.IS": "Reeder Teknoloji A.Ş.",
        },
        "transportation_sector": {
            "PASEU.IS": "Pasifik Eurasia Lojistik A.Ş.",
            "TAVHL.IS": "TAV Havalimanları Holding A.Ş.",
            "PGSUS.IS": "Pegasus Hava Taşımacılığı A.Ş.",
            "CLEBI.IS": "Çelebi Hava Servisi A.Ş.",
            "THYAO.IS": "Türk Hava Yolları A.O.",
        },
        "health_sector": {
            "ECILC.IS": "EİS Eczacıbaşı İlaç Sanayi ve Ticaret A.Ş.",
            "MPARK.IS": "MLP Sağlık Hizmetleri A.Ş.",
        },
        "retail_sector": {
            "BIMAS.IS": "BİM Birleşik Mağazalar A.Ş.",
            "DOHOL.IS": "Doğan Şirketler Grubu Holding A.Ş.",
            "SOKM.IS": "Şok Marketler Ticaret A.Ş.",
            "MGROS.IS": "Migros Ticaret A.Ş.",
            "DOAS.IS": "Doğuş Otomotiv Servis ve Ticaret A.Ş.",
        },
        "finance_sector": {
            "YKBNK.IS": "Yapı ve Kredi Bankası A.Ş.",
            "VAKBN.IS": "Türkiye Vakıflar Bankası T.A.O.",
            "ALARK.IS": "Alarko Holding A.Ş.",
            "ISCTR.IS": "Türkiye İş Bankası A.Ş.",
            "ANHYT.IS": "Anadolu Hayat Emeklilik A.Ş.",
            "ISMEN.IS": "İş Yatırım Menkul Değerler A.Ş.",
            "TSKB.IS": "Türkiye Sınai Kalkınma Bankası A.Ş.",
            "EKGYO.IS": "Emlak Konut Gayrimenkul Yatırım Ortaklığı A.Ş.",
            "AKBNK.IS": "Akbank T.A.Ş.",
            "ANSGR.IS": "Anadolu Anonim Türk Sigorta Şirketi",
            "SAHOL.IS": "Hacı Ömer Sabancı Holding A.Ş.",
            "SKBNK.IS": "Şekerbank T.A.Ş.",
            "LIDER.IS": "LDR Turizm A.Ş.",
            "GARAN.IS": "Türkiye Garanti Bankası A.Ş.",
            "HALKB.IS": "Türkiye Halk Bankası A.Ş.",
            "TURSG.IS": "Türkiye Sigorta A.Ş.",
        },
        "non_energy_minerals_sector": {
            "CIMSA.IS": "Çimsa Çimento Sanayi ve Ticaret A.Ş.",
            "BRSAN.IS": "Borusan Mannesmann Boru Sanayi ve Ticaret A.Ş.",
            "KOZAA.IS": "Koza Anadolu Metal Madencilik İşletmeleri A.Ş.",
            "OYAKC.IS": "Oyak Çimento Fabrikaları A.Ş.",
            "BSOKE.IS": "Batısöke Söke Çimento Sanayi ve Ticaret A.Ş.",
            "KONYA.IS": "Konya Çimento Sanayi A.Ş.",
            "GOLTS.IS": "Göltaş Göller Bölgesi Çimento Sanayi ve Ticaret A.Ş.",
            "BTCIM.IS": "Batıçim Batı Anadolu Çimento Sanayi A.Ş.",
            "EREGL.IS": "Ereğli Demir ve Çelik Fabrikaları T.A.Ş.",
            "CVKMD.IS": "CVK Maden İşletmeleri Sanayi ve Ticaret A.Ş.",
            "KOZAL.IS": "Koza Altın İşletmeleri A.Ş.",
            "KRDMD.IS": "Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş.",
            "KCAER.IS": "Kocaer Çelik Sanayi ve Ticaret A.Ş.",
        },
        "energy_minerals_sector": {
            "KCHOL.IS": "Koç Holding A.Ş.",
            "TUPRS.IS": "Tüpraş - Türkiye Petrol Rafinerileri A.Ş.",
        },
        "electronic_technology_sector": {
            "GESAN.IS": "Girişim Elektrik Sanayi Taahhüt ve Ticaret A.Ş.",
            "ALTNY.IS": "Altınay Savunma Teknolojileri A.Ş.",
            "ASELS.IS": "Aselsan Elektronik Sanayi ve Ticaret A.Ş.",
            "SDTTR.IS": "SDT Uzay ve Savunma Teknolojileri A.Ş.",
            "SMRTG.IS": "Smart Güneş Enerjisi Teknolojileri Araştırma Geliştirme Üretim Sanayi ve Ticaret A.Ş.",
            "CWENE.IS": "CW Enerji Mühendislik Ticaret ve Sanayi A.Ş.",
        },
        "electricity_water_gas_services_sector": {
            "ALFAS.IS": "Alfa Solar Enerji Sanayi ve Ticaret A.Ş.",
            "ODAS.IS": "Odaş Elektrik Üretim Sanayi Ticaret A.Ş.",
            "ENERY.IS": "Enerya Enerji A.Ş.",
            "AKFYE.IS": "Akfen Yenilenebilir Enerji A.Ş.",
            "YEOTK.IS": "Yeo Teknoloji Enerji ve Endüstri A.Ş.",
            "KONTR.IS": "Kontrolmatik Teknoloji Enerji ve Mühendislik A.Ş.",
            "ENJSA.IS": "Enerjisa Enerji A.Ş.",
            "CANTE.IS": "Çan2 Termik A.Ş.",
            "ZOREN.IS": "Zorlu Enerji Elektrik Üretim A.Ş.",
            "MAGEN.IS": "Margün Enerji Üretim Sanayi ve Ticaret A.Ş.",
            "AKSEN.IS": "Aksa Enerji Üretim A.Ş.",
        },
        "distribution_services_sector": {
            "SELEC.IS": "Selçuk Ecza Deposu Ticaret ve Sanayi A.Ş."
        },
        "durable_consumer_goods_sector": {
            "SISE.IS": "Türkiye Şişe ve Cam Fabrikaları A.Ş.",
            "ARCLK.IS": "Arçelik A.Ş.",
            "VESTL.IS": "Vestel Elektronik Sanayi ve Ticaret A.Ş.",
            "FROTO.IS": "Ford Otomotiv Sanayi A.Ş.",
            "TOASO.IS": "Tofaş Türk Otomobil Fabrikası A.Ş.",
            "OTKAR.IS": "Otokar Otomotiv ve Savunma Sanayi A.Ş.",
        },
        "non_durable_consumer_goods_sector": {
            "ULKER.IS": "Ülker Bisküvi Sanayi A.Ş.",
            "AGHOL.IS": "AG Anadolu Grubu Holding A.Ş.",
            "MAVI.IS": "Mavi Giyim Sanayi ve Ticaret A.Ş.",
            "AEFES.IS": "Anadolu Efes Biracılık ve Malt Sanayi A.Ş.",
            "CCOLA.IS": "Coca-Cola İçecek A.Ş.",
            "TUKAS.IS": "Tukaş Gıda Sanayi ve Ticaret A.Ş.",
        },
    },
    "cryptocurrency": {
        "BTC-USD": "Bitcoin USD",
        "ETH-USD": "Ethereum USD",
        "XRP-USD": "XRP USD",
        "BNB-USD": "BNB USD",
        "SOL-USD": "Solana USD",
        "ADA-USD": "Cardano USD",
        "DOGE-USD": "Dogecoin USD",
        "TRX-USD": "TRON USD",
        "HBAR-USD": "Hedera USD",
        "XLM-USD": "Stellar USD",
        "AVAX-USD": "Avalanche USD",
    },
    "US Stock Market": {
        "NVDA": "NVIDIA Corporation",
        "INTC": "Intel Corporation",
        "LCID": "Lucid Group, Inc.",
        "PLTR": "Palantir Technologies Inc.",
        "TSLA": "Tesla, Inc.",
        "SMCI": "Super Micro Computer, Inc.",
        "NU": "Nu Holdings Ltd.",
        "BBD": "Banco Bradesco S.A.",
        "AAL": "American Airlines Group Inc.",
        "BTG": "B2Gold Corp.",
        "MARA": "MARA Holdings, Inc.",
        "NIO": "NIO Inc.",
        "BAC": "Bank of America Corporation",
        "LYG": "Lloyds Banking Group plc",
        "IQ": "iQIYI, Inc.",
        "PSLV": "Sprott Physical Silver Trust",
        "T": "AT&T Inc.",
        "ABEV": "Ambev S.A.",
        "AAPL": "Apple Inc.",
        "WBD": "Warner Bros. Discovery, Inc.",
        "SOFI": "SoFi Technologies, Inc.",
    },
}

module.exports = bist100;